# Generated by Django 4.2.7 on 2023-11-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0004_alter_student_accountnumber_alter_student_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollnumber',
            field=models.IntegerField(default=0),
        ),
    ]
