# Generated by Django 4.2.7 on 2023-11-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0005_alter_student_rollnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dateofpayment',
            field=models.DateField(default='2023-11-27'),
        ),
        migrations.AlterField(
            model_name='student',
            name='accountnumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollnumber',
            field=models.IntegerField(),
        ),
    ]
